# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupSegmentPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='usergroup_segment_usergroupsegmentpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='label')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
